<?php
Dict::Add('RU RU', 'Russian', 'Русский', array(
    'Menu:AuditSystem' => 'Система аудита',
    'Menu:AuditSystem+' => 'Синхронизация организаций и пользователей, агенты и токены, создание аудитов, обновление каталога уязвимостей NVD и выгрузок OVAL',

    'Menu:AuditMenu' => 'Аудиты',
    'Menu:AuditMenu+' => 'Список созданных аудитов',

    'Menu:AgentsMenu' => 'Агенты',
    'Menu:AgentsMenu+' => 'Список установленных агентов',

    'Menu:AgentTokensMenu' => 'Регистрационный токен агента',
    'Menu:AgentTokensMenu+' => 'Создание регистрационного токена агента',

    'Menu:SyncJobsMenu' => 'Синхронизация организаций',
    'Menu:SyncJobsMenu+' => 'Создание заданий на синхронизацию организаций с системой аудита',

    'Menu:UserSyncJobsMenu' => 'Синхронизация пользователей',
    'Menu:UserSyncJobsMenu+' => 'Создание заданий на синхронизацию внешних пользователей с системой аудита',

    'Menu:UserAuditsSyncJobsMenu' => 'Синхронизация аудитов пользователей',
    'Menu:UserAuditsSyncJobsMenu+' => 'Создание заданий на синхронизацию аудитов пользователя с системой аудита',

    'Menu:AgentSyncJobsMenu' => 'Синхронизация агентов',
    'Menu:AgentSyncJobsMenu+' => 'Создание заданий на синхронизацию агентов с системой аудита',

    'Menu:AuditCreateJobsMenu' => 'Создание аудитов',
    'Menu:AuditCreateJobsMenu+' => 'Задания на создание аудита в системе аудита',

    'Menu:NvdSyncJobsMenu' => 'Синхронизация базы уязвимостей NVD',
    'Menu:NvdSyncJobsMenu+' => 'Запуск полной или инкрементальной синхронизации базы уязвимостей NVD',

    'Menu:OvalFeedImportJobsMenu' => 'Импорт OVAL',
    'Menu:OvalFeedImportJobsMenu+' => 'Запуск импорта OVAL выгрузок',

    'Menu:OvalFeedStateMenu' => 'Состояние OVAL выгрузок',
    'Menu:OvalFeedStateMenu+' => 'Снимки состояния OVAL по каждой выгрузке',

    'Menu:OvalImportJobMenu' => 'Запуски импорта OVAL',
    'Menu:OvalImportJobMenu+' => 'Журнал заданий импорта OVAL',

    'Menu:NvdFeedStateMenu' => 'Состояние выгрузок NVD',
    'Menu:NvdFeedStateMenu+' => 'Актуальное состояние синхронизации каждой выгрузки базы уязвимостей NVD',

    'Menu:NvdImportJobMenu' => 'Журнал импорта NVD',
    'Menu:NvdImportJobMenu+' => 'Записи заданий импорта каталога NVD (состояние и прогресс синхронизации)',

    'Menu:NvdScheduleConfigMenu' => 'Расписания NVD',
    'Menu:NvdScheduleConfigMenu+' => 'Управление расписаниями синхронизации NVD',

    'Class:AuditAgent' => 'Агент аудита',
    'Class:AuditAgent+' => 'Зарегистрированный аудиторский агент (хост с установленным ПО для сбора данных)',
    'Class:AuditAgent/Attribute:organization' => 'Организация',
    'Class:AuditAgent/Attribute:organization+' => 'Владелец агента',
    'Class:AuditAgent/Attribute:public_id' => 'Идентификатор агента',
    'Class:AuditAgent/Attribute:public_id+' => 'Уникальное значение агента',
    'Class:AuditAgent/Attribute:os_type' => 'Операционная система',
    'Class:AuditAgent/Attribute:os_type+' => 'Операционная система хоста, на котором установлен агент',

    'Class:AuditOrgSyncJob' => 'Синхронизация организаций',
    'Class:AuditOrgSyncJob+' => 'Ручной запуск синхронизации организаций в систему аудита',
    'Class:AuditOrgSyncJob/Attribute:name' => 'Название',
    'Class:AuditOrgSyncJob/Attribute:name+' => 'Произвольное название задания (например, по имени организации)',
    'Class:AuditOrgSyncJob/Attribute:organization' => 'Организация',
    'Class:AuditOrgSyncJob/Attribute:organization+' => 'Организация, которую нужно синхронизировать с системой аудита',

    'Class:AuditUserSyncJob' => 'Синхронизация пользователей',
    'Class:AuditUserSyncJob+' => 'Ручной запуск синхронизации внешних пользователей в систему аудита',
    'Class:AuditUserSyncJob/Attribute:name' => 'Название',
    'Class:AuditUserSyncJob/Attribute:name+' => 'Произвольное название задания (например, по имени пользователя)',
    'Class:AuditUserSyncJob/Attribute:user' => 'Пользователь',
    'Class:AuditUserSyncJob/Attribute:user+' => 'Внешний пользователь iTop, для которого будет создан аккаунт в системе аудита',

    'Class:AuditAgentToken' => 'Регистрационный токен агента',
    'Class:AuditAgentToken+' => 'Токен регистрации для подключения аудиторских агентов',
    'Class:AuditAgentToken/Attribute:friendly_name' => 'Название токена',
    'Class:AuditAgentToken/Attribute:friendly_name+' => 'Удобочитаемое название токена регистрации',
    'Class:AuditAgentToken/Attribute:ttl_minutes' => 'Срок действия (мин)',
    'Class:AuditAgentToken/Attribute:ttl_minutes+' => 'Через сколько минут после выдачи токен регистрации перестает действовать',
    'Class:AuditAgentToken/Attribute:expires_at' => 'Истекает',
    'Class:AuditAgentToken/Attribute:expires_at+' => 'Момент истечения срока действия токена',

    'Class:AuditUserMapping' => 'Сопоставление пользователя',
    'Class:AuditUserMapping+' => 'Связь учетной записи UserExternal в iTop с пользователем в системе аудита',
    'Class:AuditUserMapping/Attribute:user' => 'Пользователь (UserExternal)',
    'Class:AuditUserMapping/Attribute:user+' => 'Внешний пользователь iTop, для которого известен идентификатор в системе аудита',
    'Class:AuditUserMapping/Attribute:auditor_user_id' => 'ID пользователя в системе аудита',

    'Class:CustomAudit' => 'Аудиты пользователя',
    'Class:CustomAudit+' => 'Список аудитов, выполненных для пользователя в системе аудита. Готовый отчет доступен во вкладке «Вложения» (если включен модуль вложений).',
    'Class:CustomAudit/Attribute:organization' => 'Организация',
    'Class:CustomAudit/Attribute:organization+' => 'Организация, к которой относится аудит',
    'Class:CustomAudit/Attribute:user' => 'Пользователь',
    'Class:CustomAudit/Attribute:user+' => 'Внешний пользователь iTop, для которого был выполнен аудит',
    'Class:CustomAudit/Attribute:audit_id' => 'ID аудита',
    'Class:CustomAudit/Attribute:audit_id+' => 'Числовой идентификатор аудита в системе аудита',
    'Class:CustomAudit/Attribute:status' => 'Статус',
    'Class:CustomAudit/Attribute:status+' => 'Общий статус прохождения аудита (агрегируется из фаз и сервисов аудита)',
    'Class:CustomAudit/Attribute:inventory_status' => 'Статус инвентаризации',
    'Class:CustomAudit/Attribute:inventory_status+' => 'Этап сбора установленного ПО: ожидание, выполнение, завершение или сбой (значения совпадают с кодами в API)',
    'Class:CustomAudit/Attribute:analysis_status' => 'Статус анализа',
    'Class:CustomAudit/Attribute:analysis_status+' => 'Этап анализа уязвимостей',
    'Class:CustomAudit/Attribute:report_status' => 'Статус отчета',
    'Class:CustomAudit/Attribute:report_status+' => 'Этап формирования отчета',

    'Class:CustomAudit/Attribute:status/Value:PENDING' => 'В ожидании',
    'Class:CustomAudit/Attribute:status/Value:IN_PROGRESS' => 'Выполняется',
    'Class:CustomAudit/Attribute:status/Value:COMPLETED' => 'Завершено',
    'Class:CustomAudit/Attribute:status/Value:FAILED' => 'Сбой',

    'Class:CustomAudit/Attribute:inventory_status/Value:PENDING' => 'В ожидании',
    'Class:CustomAudit/Attribute:inventory_status/Value:IN_PROGRESS' => 'Выполняется',
    'Class:CustomAudit/Attribute:inventory_status/Value:COMPLETED' => 'Завершено',
    'Class:CustomAudit/Attribute:inventory_status/Value:FAILED' => 'Сбой',

    'Class:CustomAudit/Attribute:analysis_status/Value:PENDING' => 'В ожидании',
    'Class:CustomAudit/Attribute:analysis_status/Value:IN_PROGRESS' => 'Выполняется',
    'Class:CustomAudit/Attribute:analysis_status/Value:COMPLETED' => 'Завершено',
    'Class:CustomAudit/Attribute:analysis_status/Value:FAILED' => 'Сбой',

    'Class:CustomAudit/Attribute:report_status/Value:PENDING' => 'В ожидании',
    'Class:CustomAudit/Attribute:report_status/Value:IN_PROGRESS' => 'Выполняется',
    'Class:CustomAudit/Attribute:report_status/Value:COMPLETED' => 'Завершено',
    'Class:CustomAudit/Attribute:report_status/Value:FAILED' => 'Сбой',
    'Class:CustomAudit/Attribute:created_at' => 'Создан',
    'Class:CustomAudit/Attribute:created_at+' => 'Дата и время создания аудита',
    'Class:CustomAudit/Attribute:started_at' => 'Начат',
    'Class:CustomAudit/Attribute:started_at+' => 'Дата и время начала аудита',
    'Class:CustomAudit/Attribute:completed_at' => 'Завершен',
    'Class:CustomAudit/Attribute:completed_at+' => 'Дата и время успешного завершения аудита (после отчета)',
    'Class:CustomAudit/Attribute:installed_software_count' => 'Число приложений',
    'Class:CustomAudit/Attribute:installed_software_count+' => 'Количество учтенных установленных приложений на момент инвентаризации',

    'Class:AuditUserAuditsSyncJob' => 'Синхронизация аудитов пользователя',
    'Class:AuditUserAuditsSyncJob+' => 'Ручной запуск синхронизации аудитов текущего пользователя (по контакту) в систему аудита',
    'Class:AuditUserAuditsSyncJob/Attribute:name' => 'Название',
    'Class:AuditUserAuditsSyncJob/Attribute:name+' => 'Произвольное название задания синхронизации аудитов',
    'Class:AuditUserAuditsSyncJob/Attribute:person' => 'Контакт (Person)',
    'Class:AuditUserAuditsSyncJob/Attribute:person+' => 'Человек, для которого синхронизируются аудиты (подставляется автоматически)',

    'Class:AuditAgentSyncJob' => 'Синхронизация агентов',
    'Class:AuditAgentSyncJob+' => 'Ручной запуск синхронизации агентов в систему аудита',
    'Class:AuditAgentSyncJob/Attribute:name' => 'Название',
    'Class:AuditAgentSyncJob/Attribute:name+' => 'Произвольное название задания синхронизации',
    'Class:AuditAgentSyncJob/Attribute:organization' => 'Организация',
    'Class:AuditAgentSyncJob/Attribute:organization+' => 'Организация, для которой будут синхронизированы агенты',

    'Class:NvdSyncJob' => 'Синхронизация базы уязвимостей',
    'Class:NvdSyncJob+' => 'Задание на импорт или инкрементальную синхронизацию базы уязвимостей NVD. Доступно только администратору.',
    'Class:NvdSyncJob/Attribute:name' => 'Название',
    'Class:NvdSyncJob/Attribute:name+' => 'Произвольное название задания',
    'Class:NvdSyncJob/Attribute:sync_type' => 'Тип синхронизации',
    'Class:NvdSyncJob/Attribute:sync_type+' => 'Первоначальная загрузка или инкрементальное обновление',
    'Class:NvdSyncJob/Attribute:sync_type/Value:bootstrap' => 'Первоначальная загрузка',
    'Class:NvdSyncJob/Attribute:sync_type/Value:incremental' => 'Инкрементальная синхронизация',

    'Class:OvalFeedImportJob' => 'Импорт OVAL',
    'Class:OvalFeedImportJob+' => 'Задание на запуск импорта OVAL',
    'Class:OvalFeedImportJob/Attribute:name' => 'Название',
    'Class:OvalFeedImportJob/Attribute:name+' => 'Произвольное название записи (история запусков)',
    'Class:OvalFeedImportJob/Attribute:oval_feed_selection' => 'Целевая выгрузка OVAL',
    'Class:OvalFeedImportJob/Attribute:oval_feed_selection+' => 'Поставщик и каталог выгрузки OVAL; доступен только заранее заданный список вариантов',
    'Class:OvalFeedImportJob/Attribute:oval_vendor' => 'Поставщик',
    'Class:OvalFeedImportJob/Attribute:oval_vendor+' => 'Служебное поле: подставляется автоматически по выбранной выгрузке',
    'Class:OvalFeedImportJob/Attribute:feed_path' => 'Каталог выгрузки',
    'Class:OvalFeedImportJob/Attribute:feed_path+' => 'Служебное поле: подставляется автоматически по выбранной выгрузке',

    'Class:NvdScheduleConfig' => 'Расписание синхронизации NVD',
    'Class:NvdScheduleConfig+' => 'Настройка расписаний синхронизации базы уязвимостей NVD',
    'Class:NvdScheduleConfig/Attribute:name' => 'Название',
    'Class:NvdScheduleConfig/Attribute:name+' => 'Произвольное название расписания',
    'Class:NvdScheduleConfig/Attribute:sync_type' => 'Тип синхронизации',
    'Class:NvdScheduleConfig/Attribute:sync_type+' => 'Вид синхронизации NVD, для которого задается расписание (в текущей версии — инкрементальная)',
    'Class:NvdScheduleConfig/Attribute:frequency' => 'Частота',
    'Class:NvdScheduleConfig/Attribute:frequency+' => 'Частота запуска синхронизации (ежечасно, ежедневно, еженедельно и т.д.)',
    'Class:NvdScheduleConfig/Attribute:time_of_day' => 'Время суток',
    'Class:NvdScheduleConfig/Attribute:time_of_day+' => 'Время запуска синхронизации (часы:минуты)',
    'Class:NvdScheduleConfig/Attribute:day_of_week' => 'День недели',
    'Class:NvdScheduleConfig/Attribute:day_of_week+' => 'День недели для еженедельной синхронизации',
    'Class:NvdScheduleConfig/Attribute:day_of_month' => 'День месяца',
    'Class:NvdScheduleConfig/Attribute:day_of_month+' => 'День месяца для ежемесячной синхронизации',
    'Class:NvdScheduleConfig/Attribute:custom_cron' => 'Свое выражение Cron',
    'Class:NvdScheduleConfig/Attribute:custom_cron+' => 'Полная строка расписания в формате Cron (используется при частоте «по произвольному Cron»)',
    'Class:NvdScheduleConfig/Attribute:enabled' => 'Включено',
    'Class:NvdScheduleConfig/Attribute:enabled+' => 'Признак включения расписания',
    'Class:NvdScheduleConfig/Attribute:cron_expression' => 'Cron-выражение',
    'Class:NvdScheduleConfig/Attribute:cron_expression+' => 'Итоговое Cron-выражение',
    'Class:NvdScheduleConfig/Attribute:remote_schedule_id' => 'ID расписания',
    'Class:NvdScheduleConfig/Attribute:remote_schedule_id+' => 'Служебный идентификатор расписания; в карточке не отображается, хранится для интеграции',

    'Class:NvdScheduleConfig/Attribute:sync_type/Value:incremental' => 'Инкрементальная синхронизация',
    'Class:NvdScheduleConfig/Attribute:frequency/Value:hourly' => 'Каждый час',
    'Class:NvdScheduleConfig/Attribute:frequency/Value:daily' => 'Ежедневно',
    'Class:NvdScheduleConfig/Attribute:frequency/Value:weekly' => 'Еженедельно',
    'Class:NvdScheduleConfig/Attribute:frequency/Value:monthly' => 'Ежемесячно',
    'Class:NvdScheduleConfig/Attribute:frequency/Value:custom' => 'По произвольному Cron',
    'Class:NvdScheduleConfig/Attribute:day_of_week/Value:1' => 'Понедельник',
    'Class:NvdScheduleConfig/Attribute:day_of_week/Value:2' => 'Вторник',
    'Class:NvdScheduleConfig/Attribute:day_of_week/Value:3' => 'Среда',
    'Class:NvdScheduleConfig/Attribute:day_of_week/Value:4' => 'Четверг',
    'Class:NvdScheduleConfig/Attribute:day_of_week/Value:5' => 'Пятница',
    'Class:NvdScheduleConfig/Attribute:day_of_week/Value:6' => 'Суббота',
    'Class:NvdScheduleConfig/Attribute:day_of_week/Value:7' => 'Воскресенье',

    'Class:NvdImportJob' => 'Задание импорта NVD',
    'Class:NvdImportJob+' => 'Одно задание импорта базы уязвимостей NVD (состояние и прогресс)',
    'Class:NvdImportJob/Attribute:type' => 'Тип синхронизации',
    'Class:NvdImportJob/Attribute:type+' => 'Режим: bootstrap (полная первичная загрузка) или incremental (инкрементальное обновление)',
    'Class:NvdImportJob/Attribute:status' => 'Статус',
    'Class:NvdImportJob/Attribute:status+' => 'Состояние жизненного цикла задания импорта',
    'Class:NvdImportJob/Attribute:current_year' => 'Год (bootstrap)',
    'Class:NvdImportJob/Attribute:current_year+' => 'Год при пошаговой загрузке годовых архивов CVE в режиме первоначальной загрузки',
    'Class:NvdImportJob/Attribute:incremental' => 'Идентификатор инкрементальной выгрузки',
    'Class:NvdImportJob/Attribute:incremental+' => 'Какой поток данных NVD обрабатывается при инкрементальной синхронизации (например, Modified)',
    'Class:NvdImportJob/Attribute:processed_records' => 'Обработано записей',
    'Class:NvdImportJob/Attribute:processed_records+' => 'Счетчик обработанных записей на момент последнего обновления',
    'Class:NvdImportJob/Attribute:error_message' => 'Сообщение об ошибке',
    'Class:NvdImportJob/Attribute:error_message+' => 'Текст ошибки при сбое импорта',
    'Class:NvdImportJob/Attribute:started_at' => 'Начато',
    'Class:NvdImportJob/Attribute:started_at+' => 'Дата и время начала импорта',
    'Class:NvdImportJob/Attribute:finished_at' => 'Завершено',
    'Class:NvdImportJob/Attribute:finished_at+' => 'Дата и время завершения импорта',
    'Class:NvdImportJob/Attribute:updated_at' => 'Обновлено',
    'Class:NvdImportJob/Attribute:updated_at+' => 'Метка времени последнего обновления объекта в iTop',

    'Class:NvdImportJob/Attribute:type/Value:bootstrap' => 'Первоначальная загрузка',
    'Class:NvdImportJob/Attribute:type/Value:incremental' => 'Инкрементальная синхронизация',
    'Class:NvdImportJob/Attribute:status/Value:PENDING' => 'В ожидании',
    'Class:NvdImportJob/Attribute:status/Value:RUNNING' => 'Выполняется',
    'Class:NvdImportJob/Attribute:status/Value:COMPLETED' => 'Завершено',
    'Class:NvdImportJob/Attribute:status/Value:FAILED' => 'Сбой',
    'Class:NvdImportJob/Attribute:status/Value:CANCELLED' => 'Отменено',

    'Class:NvdFeedState' => 'Состояние выгрузки NVD',
    'Class:NvdFeedState+' => 'Снимок по одной выгрузке NVD',
    'Class:NvdFeedState/Attribute:feed_name' => 'Идентификатор выгрузки',
    'Class:NvdFeedState/Attribute:feed_name+' => 'Имя выгрузки NVD (например nvdcve-2.0-modified)',
    'Class:NvdFeedState/Attribute:last_modified_date' => 'Время изменения в NVD',
    'Class:NvdFeedState/Attribute:last_modified_date+' => 'Метка времени изменения выгрузки в NVD',
    'Class:NvdFeedState/Attribute:last_imported_at' => 'Время последнего успешного импорта',
    'Class:NvdFeedState/Attribute:last_imported_at+' => 'Когда выгрузка последний раз была успешно импортирована',
    'Class:NvdFeedState/Attribute:status' => 'Статус',
    'Class:NvdFeedState/Attribute:status+' => 'Состояние последней операции над выгрузкой: выполняется, успех или сбой',
    'Class:NvdFeedState/Attribute:error_message' => 'Сообщение об ошибке',
    'Class:NvdFeedState/Attribute:error_message+' => 'Текст ошибки при сбое импорта выгрузки',
    'Class:NvdFeedState/Attribute:updated_at' => 'Обновлено',
    'Class:NvdFeedState/Attribute:updated_at+' => 'Момент последнего обновления записи в iTop (не путать с временем последнего успешного импорта)',

    'Class:NvdFeedState/Attribute:status/Value:RUNNING' => 'Выполняется',
    'Class:NvdFeedState/Attribute:status/Value:SUCCESS' => 'Успешно',
    'Class:NvdFeedState/Attribute:status/Value:FAILED' => 'Сбой',

    'Class:OvalFeedState' => 'Состояние OVAL выгрузки',
    'Class:OvalFeedState+' => 'Снимок по одной OVAL выгрузке',
    'Class:OvalFeedState/Attribute:feed_key' => 'Ключ выгрузки',
    'Class:OvalFeedState/Attribute:feed_key+' => 'Уникальный ключ выгрузки OVAL',
    'Class:OvalFeedState/Attribute:vendor' => 'Поставщик',
    'Class:OvalFeedState/Attribute:vendor+' => 'Семейство выгрузок OVAL (например, Ubuntu или Debian)',
    'Class:OvalFeedState/Attribute:feed_path' => 'Каталог выгрузки',
    'Class:OvalFeedState/Attribute:feed_path+' => 'Относительный путь внутри выбранного поставщика',
    'Class:OvalFeedState/Attribute:source_url' => 'Адрес источника',
    'Class:OvalFeedState/Attribute:source_url+' => 'Адрес загрузки выгрузки OVAL',
    'Class:OvalFeedState/Attribute:fetched_at' => 'Время загрузки',
    'Class:OvalFeedState/Attribute:fetched_at+' => 'Когда выгрузка последний раз была получена',
    'Class:OvalFeedState/Attribute:rule_count' => 'Число правил OVAL',
    'Class:OvalFeedState/Attribute:rule_count+' => 'Количество правил (definition) в выгрузке после обработки',
    'Class:OvalFeedState/Attribute:last_error' => 'Последняя ошибка',
    'Class:OvalFeedState/Attribute:last_error+' => 'Текст последней ошибки при обработке выгрузки',
    'Class:OvalFeedState/Attribute:status' => 'Статус',
    'Class:OvalFeedState/Attribute:status+' => 'ОК — без ошибки при последней обработке; Ошибка — при непустом поле «Последняя ошибка»',
    'Class:OvalFeedState/Attribute:updated_at' => 'Обновлено',
    'Class:OvalFeedState/Attribute:updated_at+' => 'Момент последнего обновления записи в iTop',

    'Class:OvalFeedState/Attribute:status/Value:OK' => 'ОК',
    'Class:OvalFeedState/Attribute:status/Value:ERROR' => 'Ошибка',

    'Class:OvalImportJob' => 'Задание импорта OVAL',
    'Class:OvalImportJob+' => 'Журнал заданий импорта OVAL',
    'Class:OvalImportJob/Attribute:vendor' => 'Поставщик',
    'Class:OvalImportJob/Attribute:vendor+' => 'Семейство OVAL выгрузок',
    'Class:OvalImportJob/Attribute:feed_path' => 'Каталог выгрузки',
    'Class:OvalImportJob/Attribute:feed_path+' => 'Относительный путь внутри выбранного поставщика',
    'Class:OvalImportJob/Attribute:status' => 'Статус',
    'Class:OvalImportJob/Attribute:status+' => 'Состояние жизненного цикла задания импорта',
    'Class:OvalImportJob/Attribute:source_url' => 'Адрес источника',
    'Class:OvalImportJob/Attribute:source_url+' => 'Адрес загрузки OVAL-контента для данного задания',
    'Class:OvalImportJob/Attribute:processed_rules' => 'Обработано правил',
    'Class:OvalImportJob/Attribute:processed_rules+' => 'Счетчик обработанных правил на момент последнего обновления',
    'Class:OvalImportJob/Attribute:error_message' => 'Сообщение об ошибке',
    'Class:OvalImportJob/Attribute:error_message+' => 'Текст ошибки при сбое импорта',
    'Class:OvalImportJob/Attribute:started_at' => 'Начато',
    'Class:OvalImportJob/Attribute:started_at+' => 'Дата и время начала импорта',
    'Class:OvalImportJob/Attribute:finished_at' => 'Завершено',
    'Class:OvalImportJob/Attribute:finished_at+' => 'Дата и время завершения импорта',
    'Class:OvalImportJob/Attribute:updated_at' => 'Обновлено',
    'Class:OvalImportJob/Attribute:updated_at+' => 'Метка времени последнего обновления объекта в iTop',

    'Class:OvalImportJob/Attribute:status/Value:PENDING' => 'В ожидании',
    'Class:OvalImportJob/Attribute:status/Value:RUNNING' => 'Выполняется',
    'Class:OvalImportJob/Attribute:status/Value:COMPLETED' => 'Завершено',
    'Class:OvalImportJob/Attribute:status/Value:FAILED' => 'Сбой',
    'Class:OvalImportJob/Attribute:status/Value:CANCELLED' => 'Отменено',
)); 