<?php
Dict::Add('RU RU', 'Russian', 'Русский', array(
    'Menu:AuditConsole' => 'Консоль аудита',
    'Menu:AuditConsole+' => 'Инструменты интеграции с системой аудита',

    'Menu:AuditMenu' => 'Аудиты',
    'Menu:AuditMenu+' => 'Список созданных аудитов',

    'Menu:AgentsMenu' => 'Агенты',
    'Menu:AgentsMenu+' => 'Список установленных агентов',

    'Menu:AgentTokensMenu' => 'Регистрационный токен агента',
    'Menu:AgentTokensMenu+' => 'Создание регистрационного токена агента',

    'Menu:SyncJobsMenu' => 'Синхронизация организаций',
    'Menu:SyncJobsMenu+' => 'Создание заданий на синхронизацию организаций с системой аудита',

    'Menu:UserSyncJobsMenu' => 'Синхронизация пользователей',
    'Menu:UserSyncJobsMenu+' => 'Создание заданий на синхронизацию внешних пользователей с системой аудита',

    'Menu:UserAuditsSyncJobsMenu' => 'Синхронизация аудитов пользователей',
    'Menu:UserAuditsSyncJobsMenu+' => 'Создание заданий на синхронизацию аудитов пользователя с системой аудита',

    'Menu:AgentSyncJobsMenu' => 'Синхронизация агентов',
    'Menu:AgentSyncJobsMenu+' => 'Создание заданий на синхронизацию агентов с системой аудита',

    'Menu:AuditCreateJobsMenu' => 'Создание аудитов',
    'Menu:AuditCreateJobsMenu+' => 'Задания на создание аудита в системе аудита',

    'Menu:NvdSyncJobsMenu' => 'Синхронизация базы уязвимостей',
    'Menu:NvdSyncJobsMenu+' => 'Импорт и синхронизация базы уязвимостей',

    'Menu:NvdFeedStateMenu' => 'История состояния NVD Feed',
    'Menu:NvdFeedStateMenu+' => 'Состояние выгрузок NVD',

    'Menu:NvdImportJobMenu' => 'История запусков синхронизации NVD',
    'Menu:NvdImportJobMenu+' => 'История заданий импорта NVD',

    'Menu:NvdScheduleConfigMenu' => 'Расписания NVD',
    'Menu:NvdScheduleConfigMenu+' => 'Управление расписаниями синхронизации NVD',

    'Class:AuditAgent' => 'Агенты',
    'Class:AuditAgent+' => 'Список установленных агентов',
    'Class:AuditAgent/Attribute:organization' => 'Организация',
    'Class:AuditAgent/Attribute:organization+' => 'Владелец агента',
    'Class:AuditAgent/Attribute:public_id' => 'Идентификатор агента',
    'Class:AuditAgent/Attribute:public_id+' => 'Уникальное значение агента',
    'Class:AuditAgent/Attribute:os_type' => 'Операционная система',
    'Class:AuditAgent/Attribute:os_type+' => 'Операционная система хоста, на котором установлен агент',

    'Class:AuditOrgSyncJob' => 'Синхронизация организаций',
    'Class:AuditOrgSyncJob+' => 'Ручной запуск синхронизации организаций в систему аудита',
    'Class:AuditOrgSyncJob/Attribute:name' => 'Название',
    'Class:AuditOrgSyncJob/Attribute:name+' => 'Произвольное название задания синхронизации',

    'Class:AuditUserSyncJob' => 'Синхронизация пользователей',
    'Class:AuditUserSyncJob+' => 'Ручной запуск синхронизации внешних пользователей в систему аудита',
    'Class:AuditUserSyncJob/Attribute:name' => 'Название',
    'Class:AuditUserSyncJob/Attribute:name+' => 'Произвольное название задания синхронизации',
    'Class:AuditUserSyncJob/Attribute:user' => 'Пользователь',
    'Class:AuditUserSyncJob/Attribute:user+' => 'Внешний пользователь iTop, для которого будет создан аккаунт в системе аудита',

    'Class:AuditAgentToken' => 'Регистрационный токен агента',
    'Class:AuditAgentToken+' => 'Токен регистрации для подключения аудиторских агентов',
    'Class:AuditAgentToken/Attribute:friendly_name' => 'Название токена',
    'Class:AuditAgentToken/Attribute:friendly_name+' => 'Удобочитаемое название токена регистрации',
    'Class:AuditAgentToken/Attribute:ttl_minutes' => 'Время жизни (минуты)',
    'Class:AuditAgentToken/Attribute:ttl_minutes+' => 'Сколько минут действителен токен регистрации',
    'Class:AuditAgentToken/Attribute:expires_at' => 'Истекает',
    'Class:AuditAgentToken/Attribute:expires_at+' => 'Момент истечения срока действия токена',

    'Class:AuditUserMapping' => 'Маппинг пользователя аудита',
    'Class:AuditUserMapping+' => 'Связь учетной записи UserExternal в iTop с id пользователя в auditor-service',
    'Class:AuditUserMapping/Attribute:user' => 'Пользователь (UserExternal)',
    'Class:AuditUserMapping/Attribute:user+' => 'Учетная запись iTop, для которой сохранен id в auditor-service',
    'Class:AuditUserMapping/Attribute:auditor_user_id' => 'Id в auditor-service',

    'Class:CustomAudit' => 'Аудиты пользователя',
    'Class:CustomAudit+' => 'Список аудитов, выполненных для пользователя в системе аудита',
    'Class:CustomAudit/Attribute:organization' => 'Организация',
    'Class:CustomAudit/Attribute:organization+' => 'Организация, к которой относится аудит',
    'Class:CustomAudit/Attribute:user' => 'Пользователь',
    'Class:CustomAudit/Attribute:user+' => 'Внешний пользователь iTop, для которого был выполнен аудит',
    'Class:CustomAudit/Attribute:audit_id' => 'Id аудита',
    'Class:CustomAudit/Attribute:audit_id+' => 'Идентификатор аудита в системе аудита',
    'Class:CustomAudit/Attribute:status' => 'Статус',
    'Class:CustomAudit/Attribute:status+' => 'Текущий статус аудита в системе аудита',
    'Class:CustomAudit/Attribute:created_at' => 'Создан',
    'Class:CustomAudit/Attribute:created_at+' => 'Дата и время создания аудита',
    'Class:CustomAudit/Attribute:started_at' => 'Начат',
    'Class:CustomAudit/Attribute:started_at+' => 'Дата и время начала аудита',
    'Class:CustomAudit/Attribute:completed_at' => 'Завершен',
    'Class:CustomAudit/Attribute:completed_at+' => 'Дата и время завершения аудита',
    'Class:CustomAudit/Attribute:installed_software_count' => 'Кол-во ПО',
    'Class:CustomAudit/Attribute:installed_software_count+' => 'Количество установленных программ, найденных в ходе аудита',

    'Class:AuditUserAuditsSyncJob' => 'Синхронизация аудитов пользователя',
    'Class:AuditUserAuditsSyncJob+' => 'Ручной запуск синхронизации аудитов текущего пользователя (по контакту) в систему аудита',
    'Class:AuditUserAuditsSyncJob/Attribute:name' => 'Название',
    'Class:AuditUserAuditsSyncJob/Attribute:name+' => 'Произвольное название задания синхронизации аудитов',
    'Class:AuditUserAuditsSyncJob/Attribute:person' => 'Контакт (Person)',
    'Class:AuditUserAuditsSyncJob/Attribute:person+' => 'Человек, для которого синхронизируются аудиты (подставляется автоматически)',

    'Class:AuditAgentSyncJob' => 'Синхронизация агентов',
    'Class:AuditAgentSyncJob+' => 'Ручной запуск синхронизации агентов в систему аудита',
    'Class:AuditAgentSyncJob/Attribute:name' => 'Название',
    'Class:AuditAgentSyncJob/Attribute:name+' => 'Произвольное название задания синхронизации',
    'Class:AuditAgentSyncJob/Attribute:organization' => 'Организация',
    'Class:AuditAgentSyncJob/Attribute:organization+' => 'Организация, для которой будут синхронизированы агенты',

    'Class:NvdSyncJob' => 'Синхронизация базы уязвимостей',
    'Class:NvdSyncJob+' => 'Задание на импорт или инкрементальную синхронизацию базы уязвимостей в analyzer-service. Доступно только администратору.',
    'Class:NvdSyncJob/Attribute:name' => 'Название',
    'Class:NvdSyncJob/Attribute:name+' => 'Произвольное название задания',
    'Class:NvdSyncJob/Attribute:sync_type' => 'Тип синхронизации',
    'Class:NvdSyncJob/Attribute:sync_type+' => 'Первоначальная загрузка (bootstrap) или инкрементальное обновление (incremental)',
    'Enum:NvdSyncJob/sync_type/bootstrap' => 'Первоначальная загрузка',
    'Enum:NvdSyncJob/sync_type/incremental' => 'Инкрементальная синхронизация',

    'Class:NvdScheduleConfig' => 'Расписание синхронизации NVD',
    'Class:NvdScheduleConfig+' => 'Настройка расписаний синхронизации базы уязвимостей в analyzer-service',
    'Class:NvdScheduleConfig/Attribute:name' => 'Название',
    'Class:NvdScheduleConfig/Attribute:name+' => 'Произвольное название расписания',
    'Class:NvdScheduleConfig/Attribute:sync_type' => 'Тип синхронизации',
    'Class:NvdScheduleConfig/Attribute:sync_type+' => 'Тип синхронизации, для которой применяется данное расписание',
    'Class:NvdScheduleConfig/Attribute:frequency' => 'Частота',
    'Class:NvdScheduleConfig/Attribute:frequency+' => 'Частота запуска синхронизации (ежечасно, ежедневно, еженедельно и т.д.)',
    'Class:NvdScheduleConfig/Attribute:time_of_day' => 'Время суток',
    'Class:NvdScheduleConfig/Attribute:time_of_day+' => 'Время запуска синхронизации (часы:минуты)',
    'Class:NvdScheduleConfig/Attribute:day_of_week' => 'День недели',
    'Class:NvdScheduleConfig/Attribute:day_of_week+' => 'День недели для еженедельной синхронизации',
    'Class:NvdScheduleConfig/Attribute:day_of_month' => 'День месяца',
    'Class:NvdScheduleConfig/Attribute:day_of_month+' => 'День месяца для ежемесячной синхронизации',
    'Class:NvdScheduleConfig/Attribute:custom_cron' => 'Произвольный cron',
    'Class:NvdScheduleConfig/Attribute:custom_cron+' => 'Произвольное cron-выражение для нестандартного расписания',
    'Class:NvdScheduleConfig/Attribute:enabled' => 'Включено',
    'Class:NvdScheduleConfig/Attribute:enabled+' => 'Признак включения расписания',
    'Class:NvdScheduleConfig/Attribute:cron_expression' => 'Cron-выражение',
    'Class:NvdScheduleConfig/Attribute:cron_expression+' => 'Фактическое cron-выражение, отправляемое в analyzer-service',
    'Class:NvdScheduleConfig/Attribute:remote_schedule_id' => 'Id расписания в analyzer-service',
    'Class:NvdScheduleConfig/Attribute:remote_schedule_id+' => 'Идентификатор соответствующего расписания в analyzer-service',

    'Class:NvdImportJob' => 'Задание импорта NVD',
    'Class:NvdImportJob+' => 'Одно задание импорта базы уязвимостей NVD (состояние и прогресс)',
    'Class:NvdImportJob/Attribute:type' => 'Тип синхронизации',
    'Class:NvdImportJob/Attribute:type+' => 'Тип запуска: первоначальная загрузка (bootstrap) или инкрементальное обновление (incremental)',
    'Class:NvdImportJob/Attribute:status' => 'Статус',
    'Class:NvdImportJob/Attribute:status+' => 'Текущий статус задания',
    'Class:NvdImportJob/Attribute:current_year' => 'Год',
    'Class:NvdImportJob/Attribute:current_year+' => 'Год при пошаговой загрузке годовых выгрузок CVE',
    'Class:NvdImportJob/Attribute:incremental' => 'Инкрементальная выгрузка',
    'Class:NvdImportJob/Attribute:incremental+' => 'Какой набор данных обрабатывается в данном инкрементальном запуске (например, CVE-Modified - недавно измененные CVE)',
    'Class:NvdImportJob/Attribute:processed_records' => 'Обработано записей',
    'Class:NvdImportJob/Attribute:processed_records+' => 'Количество обработанных записей на момент последнего обновления',
    'Class:NvdImportJob/Attribute:error_message' => 'Сообщение об ошибке',
    'Class:NvdImportJob/Attribute:error_message+' => 'Текст ошибки при сбое импорта',
    'Class:NvdImportJob/Attribute:started_at' => 'Начато',
    'Class:NvdImportJob/Attribute:started_at+' => 'Дата и время начала импорта',
    'Class:NvdImportJob/Attribute:finished_at' => 'Завершено',
    'Class:NvdImportJob/Attribute:finished_at+' => 'Дата и время завершения импорта',
    'Class:NvdImportJob/Attribute:updated_at' => 'Обновлено',
    'Class:NvdImportJob/Attribute:updated_at+' => 'Момент последнего обновления записи',

    'Class:NvdFeedState' => 'Состояние выгрузки NVD',
    'Class:NvdFeedState+' => 'Снимок по одной выгрузке NVD',
    'Class:NvdFeedState/Attribute:feed_name' => 'Имя выгрузки (feed)',
    'Class:NvdFeedState/Attribute:feed_name+' => 'Идентификатор выгрузки NVD (например, nvdcve-2.0-modified)',
    'Class:NvdFeedState/Attribute:last_modified_date' => 'Дата изменения в NVD',
    'Class:NvdFeedState/Attribute:last_modified_date+' => 'Метка lastModified из источника NVD для данной выгрузки',
    'Class:NvdFeedState/Attribute:last_imported_at' => 'Последний импорт',
    'Class:NvdFeedState/Attribute:last_imported_at+' => 'Когда данная выгрузка была успешно импортирована',
    'Class:NvdFeedState/Attribute:status' => 'Статус',
    'Class:NvdFeedState/Attribute:status+' => 'Статус последней операции импорта',
    'Class:NvdFeedState/Attribute:error_message' => 'Сообщение об ошибке',
    'Class:NvdFeedState/Attribute:error_message+' => 'Текст ошибки при сбое импорта выгрузки',
    'Class:NvdFeedState/Attribute:updated_at' => 'Обновлено',
    'Class:NvdFeedState/Attribute:updated_at+' => 'Момент последнего обновления записи',
));