<?php
Dict::Add('RU RU', 'Russian', 'Русский', array(
    'Menu:AuditConsole' => 'Консоль аудита',
    'Menu:AuditConsole+' => 'Инструменты интеграции с системой аудита',

    'Menu:AuditMenu' => 'Аудиты',
    'Menu:AuditMenu+' => 'Список созданных аудитов',

    'Menu:AgentsMenu' => 'Агенты',
    'Menu:AgentsMenu+' => 'Список установленных агентов',

    'Menu:AgentTokensMenu' => 'Регистрационный токен агента',
    'Menu:AgentTokensMenu+' => 'Создание регистрационного токена агента',

    'Menu:SyncJobsMenu' => 'Синхронизация организаций',
    'Menu:SyncJobsMenu+' => 'Создание заданий на синхронизацию организаций с системой аудита',

    'Menu:UserSyncJobsMenu' => 'Синхронизация пользователей',
    'Menu:UserSyncJobsMenu+' => 'Создание заданий на синхронизацию внешних пользователей с системой аудита',

    'Menu:UserAuditsSyncJobsMenu' => 'Синхронизация аудитов пользователей',
    'Menu:UserAuditsSyncJobsMenu+' => 'Создание заданий на синхронизацию аудитов пользователя с системой аудита',

    'Menu:AgentSyncJobsMenu' => 'Синхронизация агентов',
    'Menu:AgentSyncJobsMenu+' => 'Создание заданий на синхронизацию агентов с системой аудита',

    'Menu:AuditCreateJobsMenu' => 'Создание аудитов',
    'Menu:AuditCreateJobsMenu+' => 'Задания на создание аудита в системе аудита',

    'Menu:NvdSyncJobsMenu' => 'Синхронизация базы уязвимостей',
    'Menu:NvdSyncJobsMenu+' => 'Импорт и синхронизация базы уязвимостей',

    'Class:AuditAgent' => 'Агенты',
    'Class:AuditAgent+' => 'Список установленных агентов',
    'Class:AuditAgent/Attribute:organization' => 'Организация',
    'Class:AuditAgent/Attribute:organization+' => 'Владелец агента',
    'Class:AuditAgent/Attribute:public_id' => 'Идентификатор агента',
    'Class:AuditAgent/Attribute:public_id+' => 'Уникальное значение агента',
    'Class:AuditAgent/Attribute:os_type' => 'Операционная система',
    'Class:AuditAgent/Attribute:os_type+' => 'Операционная система хоста, на котором установлен агент',

    'Class:AuditOrgSyncJob' => 'Синхронизация организаций',
    'Class:AuditOrgSyncJob+' => 'Ручной запуск синхронизации организаций в систему аудита',
    'Class:AuditOrgSyncJob/Attribute:name' => 'Название',
    'Class:AuditOrgSyncJob/Attribute:name+' => 'Произвольное название задания синхронизации',

    'Class:AuditUserSyncJob' => 'Синхронизация пользователей',
    'Class:AuditUserSyncJob+' => 'Ручной запуск синхронизации внешних пользователей в систему аудита',
    'Class:AuditUserSyncJob/Attribute:name' => 'Название',
    'Class:AuditUserSyncJob/Attribute:name+' => 'Произвольное название задания синхронизации',
    'Class:AuditUserSyncJob/Attribute:user' => 'Пользователь',
    'Class:AuditUserSyncJob/Attribute:user+' => 'Внешний пользователь iTop, для которого будет создан аккаунт в системе аудита',

    'Class:AuditAgentToken' => 'Регистрационный токен агента',
    'Class:AuditAgentToken+' => 'Токен регистрации для подключения аудиторских агентов',
    'Class:AuditAgentToken/Attribute:friendly_name' => 'Название токена',
    'Class:AuditAgentToken/Attribute:friendly_name+' => 'Удобочитаемое название токена регистрации',
    'Class:AuditAgentToken/Attribute:ttl_minutes' => 'Время жизни (минуты)',
    'Class:AuditAgentToken/Attribute:ttl_minutes+' => 'Сколько минут действителен токен регистрации',
    'Class:AuditAgentToken/Attribute:expires_at' => 'Истекает',
    'Class:AuditAgentToken/Attribute:expires_at+' => 'Момент истечения срока действия токена',

    'Class:AuditUserMapping' => 'Маппинг пользователя аудита',
    'Class:AuditUserMapping+' => 'Связь учетной записи UserExternal в iTop с id пользователя в auditor-service',
    'Class:AuditUserMapping/Attribute:user' => 'Пользователь (UserExternal)',
    'Class:AuditUserMapping/Attribute:user+' => 'Учетная запись iTop, для которой сохранен id в auditor-service',
    'Class:AuditUserMapping/Attribute:auditor_user_id' => 'Id в auditor-service',

    'Class:CustomAudit' => 'Аудиты пользователя',
    'Class:CustomAudit+' => 'Список аудитов, выполненных для пользователя в системе аудита',
    'Class:CustomAudit/Attribute:organization' => 'Организация',
    'Class:CustomAudit/Attribute:organization+' => 'Организация, к которой относится аудит',
    'Class:CustomAudit/Attribute:user' => 'Пользователь',
    'Class:CustomAudit/Attribute:user+' => 'Внешний пользователь iTop, для которого был выполнен аудит',
    'Class:CustomAudit/Attribute:audit_id' => 'ID аудита',
    'Class:CustomAudit/Attribute:audit_id+' => 'Идентификатор аудита в системе аудита',
    'Class:CustomAudit/Attribute:status' => 'Статус',
    'Class:CustomAudit/Attribute:status+' => 'Текущий статус аудита в системе аудита',
    'Class:CustomAudit/Attribute:created_at' => 'Создан',
    'Class:CustomAudit/Attribute:created_at+' => 'Дата и время создания аудита',
    'Class:CustomAudit/Attribute:started_at' => 'Начат',
    'Class:CustomAudit/Attribute:started_at+' => 'Дата и время начала аудита',
    'Class:CustomAudit/Attribute:completed_at' => 'Завершён',
    'Class:CustomAudit/Attribute:completed_at+' => 'Дата и время завершения аудита',
    'Class:CustomAudit/Attribute:installed_software_count' => 'Кол-во ПО',
    'Class:CustomAudit/Attribute:installed_software_count+' => 'Количество установленных программ, найденных в ходе аудита',

    'Class:AuditUserAuditsSyncJob' => 'Синхронизация аудитов пользователя',
    'Class:AuditUserAuditsSyncJob+' => 'Ручной запуск синхронизации аудитов текущего пользователя (по контакту) в систему аудита',
    'Class:AuditUserAuditsSyncJob/Attribute:name' => 'Название',
    'Class:AuditUserAuditsSyncJob/Attribute:name+' => 'Произвольное название задания синхронизации аудитов',
    'Class:AuditUserAuditsSyncJob/Attribute:person' => 'Контакт (Person)',
    'Class:AuditUserAuditsSyncJob/Attribute:person+' => 'Человек, для которого синхронизируются аудиты (подставляется автоматически)',

    'Class:AuditAgentSyncJob' => 'Синхронизация агентов',
    'Class:AuditAgentSyncJob+' => 'Ручной запуск синхронизации агентов в систему аудита',
    'Class:AuditAgentSyncJob/Attribute:name' => 'Название',
    'Class:AuditAgentSyncJob/Attribute:name+' => 'Произвольное название задания синхронизации',
    'Class:AuditAgentSyncJob/Attribute:organization' => 'Организация',
    'Class:AuditAgentSyncJob/Attribute:organization+' => 'Организация, для которой будут синхронизированы агенты',

    'Class:NvdSyncJob' => 'Синхронизация базы уязвимостей',
    'Class:NvdSyncJob+' => 'Задание на импорт или инкрементальную синхронизацию базы уязвимостей в analyzer-service. Доступно только администратору.',
    'Class:NvdSyncJob/Attribute:name' => 'Название',
    'Class:NvdSyncJob/Attribute:name+' => 'Произвольное название задания',
    'Class:NvdSyncJob/Attribute:sync_type' => 'Тип синхронизации',
    'Class:NvdSyncJob/Attribute:sync_type+' => 'Первоначальная загрузка (bootstrap) или инкрементальное обновление (incremental)',
    'Enum:NvdSyncJob/sync_type/bootstrap' => 'Первоначальная загрузка',
    'Enum:NvdSyncJob/sync_type/incremental' => 'Инкрементальная синхронизация',
));